//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICI()
        {
            this.ALT_DEPO = new HashSet<ALT_DEPO>();
            this.ALT_DEPO1 = new HashSet<ALT_DEPO>();
            this.DEPO = new HashSet<DEPO>();
            this.DEPO1 = new HashSet<DEPO>();
            this.DEPO_ESLESTIRME = new HashSet<DEPO_ESLESTIRME>();
            this.DEPO_ESLESTIRME1 = new HashSet<DEPO_ESLESTIRME>();
            this.STOK_DURUM = new HashSet<STOK_DURUM>();
            this.STOK_DURUM1 = new HashSet<STOK_DURUM>();
            this.SORUMLU = new HashSet<SORUMLU>();
            this.SORUMLU1 = new HashSet<SORUMLU>();
            this.STOK_HAREKET = new HashSet<STOK_HAREKET>();
            this.STOK_HAREKET1 = new HashSet<STOK_HAREKET>();
            this.STOK = new HashSet<STOK>();
            this.STOK1 = new HashSet<STOK>();
        }
    
        public int KULLANICI_ID { get; set; }
        public string KUL_USERNAME { get; set; }
        public string KUL_SIFRE { get; set; }
        public string KUL_AD { get; set; }
        public string KUL_SOYAD { get; set; }
        public int KUL_TIP { get; set; }
        public bool STATU { get; set; }
        public string OLUSTURAN_KULLANICI { get; set; }
        public System.DateTime OLUSTURMA_TARIHI { get; set; }
        public string GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALT_DEPO> ALT_DEPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALT_DEPO> ALT_DEPO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPO> DEPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPO> DEPO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPO_ESLESTIRME> DEPO_ESLESTIRME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPO_ESLESTIRME> DEPO_ESLESTIRME1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_DURUM> STOK_DURUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_DURUM> STOK_DURUM1 { get; set; }
        public virtual KULLANICI_TIP KULLANICI_TIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORUMLU> SORUMLU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORUMLU> SORUMLU1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_HAREKET> STOK_HAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_HAREKET> STOK_HAREKET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK> STOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK> STOK1 { get; set; }
    }
}
