//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockEntities : DbContext
    {
        public StockEntities()
            : base("name=StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALT_DEPO> ALT_DEPO { get; set; }
        public virtual DbSet<DEPO> DEPO { get; set; }
        public virtual DbSet<DEPO_ESLESTIRME> DEPO_ESLESTIRME { get; set; }
        public virtual DbSet<HAREKET_TIP> HAREKET_TIP { get; set; }
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
        public virtual DbSet<KULLANICI_TIP> KULLANICI_TIP { get; set; }
        public virtual DbSet<OLCU_BIRIMI> OLCU_BIRIMI { get; set; }
        public virtual DbSet<SORUMLU> SORUMLU { get; set; }
        public virtual DbSet<STOK> STOK { get; set; }
        public virtual DbSet<STOK_DURUM> STOK_DURUM { get; set; }
        public virtual DbSet<STOK_HAREKET> STOK_HAREKET { get; set; }
    }
}
