//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK_DURUM
    {
        public int DURUM_ID { get; set; }
        public int STOK_ID { get; set; }
        public int DEPO_ESLESTIRME_ID { get; set; }
        public decimal DURUM_MIKTAR { get; set; }
        public int OLUSTURAN_KULLANICI { get; set; }
        public System.DateTime OLUSTURMA_TARIHI { get; set; }
        public Nullable<int> GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
    
        public virtual DEPO_ESLESTIRME DEPO_ESLESTIRME { get; set; }
        public virtual KULLANICI KULLANICI { get; set; }
        public virtual KULLANICI KULLANICI1 { get; set; }
        public virtual STOK STOK { get; set; }
    }
}
