//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOK()
        {
            this.STOK_DURUM = new HashSet<STOK_DURUM>();
            this.STOK_HAREKET = new HashSet<STOK_HAREKET>();
        }
    
        public int STOK_ID { get; set; }
        public string STOK_AD { get; set; }
        public int STOK_OLCUBIRIM { get; set; }
        public string STOK_MARKA { get; set; }
        public string STOK_DETAY { get; set; }
        public System.DateTime KAYIT_TARIHI { get; set; }
        public Nullable<decimal> MIN_MIKTAR { get; set; }
        public bool STATU { get; set; }
        public int OLUSTURAN_KULLANICI { get; set; }
        public System.DateTime OLUSTURMA_TARIHI { get; set; }
        public Nullable<int> GUNCELLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> GUNCELLEME_TARIHI { get; set; }
    
        public virtual KULLANICI KULLANICI { get; set; }
        public virtual KULLANICI KULLANICI1 { get; set; }
        public virtual OLCU_BIRIMI OLCU_BIRIMI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_DURUM> STOK_DURUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOK_HAREKET> STOK_HAREKET { get; set; }
    }
}
